version: 0.2

env:
  variables:
    CI: true

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands: npm ci
  build:
    commands: npm run build

reports:
  unit-tests:
    files:
      - tests/junit.xml
    discard-paths: yes
    file-format: JunitXml

artifacts:
  files:
    - build/**/*

cache:
  paths:
    - node_modules/**/*
