version: 0.2

env:
  variables:
    CI: true

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      npm install
  build:
    commands:
      npm run build

#reports:
  #report-name-or-arn:
    #files:
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson

artifacts:
  files:
    - build/**/*

#cache:
  #paths:
    # - paths