# [START functions_ci_cd_cloud_build]
steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', \'-t', 'gcr.io/$PROJECT_ID/cv', '.']
      timeout: 500s
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/cv']
images:
    - 'gcr.io/$PROJECT_ID/cv:latest'
# [END functions_ci_cd_cloud_build]