# [START functions_ci_cd_cloud_build]
steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/cv", "."]
    timeout: 500s
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/cv"]
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=k8s.yaml
      - --image=gcr.io/$PROJECT_ID/cv
      - --location=europe-west1-b
      - --cluster=nginx-1-cluster
images:
  - "gcr.io/$PROJECT_ID/cv:latest"
# [END functions_ci_cd_cloud_build]
